name = "FredAPI"
uuid = "320479a4-fee6-46c5-842a-b16b59b9bc21"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Compat = "3.47.0, 4"
Dates = "1.10.0"
HTTP = "1.10.19"
JSON = "1.3, 1.4"
StructUtils = "2.6.2"
TimeZones = "1.22.2"
julia = "1.10"
